name: Setup Script Test
on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        required: false
        description: 'Manually test Setup test'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ${{ github.workspace }}/setup.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
